#!/bin/bash

just lint
if [ $? -ne 0 ]; then
  echo "Linting failed. Please fix the issues before pushing."
  exit 1
fi

# check if any changes are not committed
if [[ -n $(git status --porcelain) ]]; then
  echo "You have uncommitted changes. Please commit or stash them before pushing."
  exit 1
fi
