CREATE TABLE IF NOT EXISTS author (
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS quote (
	id INTEGER PRIMARY KEY,
	text TEXT NOT NULL,
	author_id INTEGER NOT NULL,
	when_used DATETIME,
	FOREIGN KEY(author_id) REFERENCES author(id)
);
